apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::816768290812:role/jenkins-eks-role
      username: jenkins
      groups:
        - system:masters
# Note: the value {jenkins-eks-role} corresponds to the "name" field of the role created by Terraform
#       attached to the EC2 IAM profile
